name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: crazy-max/.github/.github/workflows/bake-distribute-mp.yml@0acc187b016a2946786f201397bbcfb2c530ffc7
    permissions:
      # same as global permissions
      contents: read
    with:
      target: image-all
      push: ${{ github.event_name != 'pull_request' }}
      set-meta-labels: true
      meta-image: anonaddy/anonaddy
      meta-tags: |
        type=match,pattern=(.*)-r,group=1
        type=ref,event=pr
        type=edge
      meta-labels: |
        org.opencontainers.image.title=addy.io
        org.opencontainers.image.description=Anonymous Email Forwarding
        org.opencontainers.image.vendor=CrazyMax
    secrets:
      login-username: ${{ secrets.DOCKER_USERNAME }}
      login-password: ${{ secrets.DOCKER_PASSWORD }}
